
# UV-K5 packet firmware (packet-fw branch).
#
# Every radio feature a packet station does not use has been deleted from the
# source, so there are no feature flags left. What remains is always built in:
# the flat (DIG style) audio path, the UART EEPROM protocol, the BK4819
# register read command (0x0601) and serial protocol v2. See docs/packet-fw.md.
#
#   make                 release build
#   make bench           bench build: ENABLE_UART_RAW_REG_WRITE=1
#   make VERSION_STRING=v1.2.3   set the version (at most 8 characters)
#
# Changing an option rebuilds everything (the options are recorded in
# .build-options), so release and bench builds never share objects.

# ---- BENCH OPTIONS (off in release builds) ----
# 1: build in the legacy 0x0602 command, which writes any BK4819 register
# unchecked, REG_30 (TX enable), REG_33 (PA enable) and REG_36 (PA bias)
# included, so it can put out RF outside the transmit state machine. For
# bench experiments only; never in a release. Without it 0x0602 is ignored
# like any unknown command. (Protocol v2 REG_WRITE is always built in: it
# refuses those registers.)
ENABLE_UART_RAW_REG_WRITE     ?= 0

# ---- COMPILER/LINKER OPTIONS ----
ENABLE_CLANG                  ?= 0
ENABLE_SWD                    ?= 0
ENABLE_LTO                    ?= 1

#############################################################

TARGET = firmware

ifeq ($(ENABLE_CLANG),1)
	# GCC's linker, ld, doesn't understand LLVM's generated bytecode
	ENABLE_LTO := 0
endif

BSP_DEFINITIONS := $(wildcard hardware/*/*.def)
BSP_HEADERS     := $(patsubst hardware/%,bsp/%,$(BSP_DEFINITIONS))
BSP_HEADERS     := $(patsubst %.def,%.h,$(BSP_HEADERS))

OBJS =
OBJS += start.o
OBJS += init.o
OBJS += external/printf/printf.o
OBJS += driver/adc.o
OBJS += driver/backlight.o
OBJS += driver/bk4819.o
OBJS += driver/crc.o
OBJS += driver/eeprom.o
OBJS += driver/gpio.o
OBJS += driver/i2c.o
OBJS += driver/keyboard.o
OBJS += driver/spi.o
OBJS += driver/st7565.o
OBJS += driver/system.o
OBJS += driver/systick.o
OBJS += driver/uart.o
OBJS += app/app.o
OBJS += app/events.o
OBJS += app/main.o
OBJS += app/menu.o
OBJS += app/monitor.o
OBJS += app/params.o
OBJS += app/uart.o
OBJS += app/v2.o
OBJS += bitmaps.o
OBJS += board.o
OBJS += font.o
OBJS += frequencies.o
OBJS += functions.o
OBJS += helper/battery.o
OBJS += misc.o
OBJS += outq.o
OBJS += ptt.o
OBJS += pttarb.o
OBJS += radio.o
OBJS += scheduler.o
OBJS += settings.o
OBJS += ui/battery.o
OBJS += ui/helper.o
OBJS += ui/inputbox.o
OBJS += ui/main.o
OBJS += ui/menu.o
OBJS += ui/status.o
OBJS += ui/ui.o
OBJS += ui/welcome.o
OBJS += version.o
OBJS += main.o

ifeq ($(OS), Windows_NT) # windows
    TOP := $(dir $(realpath $(lastword $(MAKEFILE_LIST))))
    RM = del /Q
    FixPath = $(subst /,\,$1)
    WHERE = where
    NULL_OUTPUT = nul
else # unix
    TOP := $(shell pwd)
    RM = rm -f
    FixPath = $1
    WHERE = which
    NULL_OUTPUT = /dev/null
endif

AS = arm-none-eabi-gcc
LD = arm-none-eabi-gcc

ifeq ($(ENABLE_CLANG),0)
	CC = arm-none-eabi-gcc
# Use GCC's linker to avoid undefined symbol errors
#	LD += arm-none-eabi-gcc
else
#	May need to adjust this to match your system
	CC = clang --sysroot=/usr/arm-none-eabi --target=arm-none-eabi
#	Bloats binaries to 512MB
#	LD = ld.lld
endif

OBJCOPY = arm-none-eabi-objcopy
SIZE = arm-none-eabi-size

AUTHOR_STRING ?= PKTFW
# the user might not have/want git installed
# can set own version string here (max 7 chars)
# Release builds pass the tag (VERSION_STRING=v1.2.3). Otherwise: the tag
# on HEAD, else the short commit hash.
ifneq (, $(shell $(WHERE) git))
	VERSION_STRING ?= $(shell git describe --tags --exact-match 2>$(NULL_OUTPUT))
	ifeq (, $(VERSION_STRING))
    	VERSION_STRING := $(shell git rev-parse --short=7 HEAD 2>$(NULL_OUTPUT))
	endif
endif
# If there is still no VERSION_STRING we need to make one.
# It is needed for the firmware packing script
ifeq (, $(VERSION_STRING))
	VERSION_STRING := NOGIT
endif
# The packed image has 16 bytes for "*PKTFW <version>" and the menu shows 8
# characters of the version.
ifneq (ok, $(shell [ $$(printf '%s' '$(VERSION_STRING)' | wc -c) -le 8 ] && echo ok))
    $(error VERSION_STRING '$(VERSION_STRING)' is longer than 8 characters)
endif


ASFLAGS = -c -mcpu=cortex-m0

CFLAGS =
ifeq ($(ENABLE_CLANG),0)
	CFLAGS += -Os -Wall -Werror -mcpu=cortex-m0 -fno-builtin -fshort-enums -fno-delete-null-pointer-checks -std=c2x -MMD
	#CFLAGS += -Os -Wall -Werror -mcpu=cortex-m0 -fno-builtin -fshort-enums -fno-delete-null-pointer-checks -std=c11 -MMD
	#CFLAGS += -Os -Wall -Werror -mcpu=cortex-m0 -fno-builtin -fshort-enums -fno-delete-null-pointer-checks -std=c99 -MMD
	#CFLAGS += -Os -Wall -Werror -mcpu=cortex-m0 -fno-builtin -fshort-enums -fno-delete-null-pointer-checks -std=gnu99 -MMD
	#CFLAGS += -Os -Wall -Werror -mcpu=cortex-m0 -fno-builtin -fshort-enums -fno-delete-null-pointer-checks -std=gnu11 -MMD
else
	# Oz needed to make it fit on flash
	CFLAGS += -Oz -Wall -Werror -mcpu=cortex-m0 -fno-builtin -fshort-enums -fno-delete-null-pointer-checks -std=c2x -MMD
endif

ifeq ($(ENABLE_LTO),1)
	CFLAGS += -flto=auto
else
	# We get most of the space savings if LTO creates problems
	CFLAGS += -ffunction-sections -fdata-sections
endif

# May cause unhelpful build failures
#CFLAGS += -Wpadded

# catch any and all warnings
CFLAGS += -Wextra
#CFLAGS += -Wpedantic

CFLAGS += -DPRINTF_INCLUDE_CONFIG_H
CFLAGS += -DAUTHOR_STRING=\"$(AUTHOR_STRING)\" -DVERSION_STRING=\"$(VERSION_STRING)\"

ifeq ($(ENABLE_SWD),1)
	CFLAGS += -DENABLE_SWD
endif

ifeq ($(ENABLE_UART_RAW_REG_WRITE),1)
	CFLAGS += -DENABLE_UART_RAW_REG_WRITE
endif

LDFLAGS =
LDFLAGS += -z noexecstack -mcpu=cortex-m0 -nostartfiles -Wl,-T,firmware.ld -Wl,--gc-sections

# Use newlib-nano instead of newlib
LDFLAGS += --specs=nano.specs

ifeq ($(DEBUG),1)
	ASFLAGS += -g
	CFLAGS  += -g
	LDFLAGS += -g
endif

INC =
INC += -I $(TOP)
INC += -I $(TOP)/external/CMSIS_5/CMSIS/Core/Include/
INC += -I $(TOP)/external/CMSIS_5/Device/ARM/ARMCM0/Include

LIBS =

DEPS = $(OBJS:.o=.d)



ifneq (, $(shell $(WHERE) python))
    MY_PYTHON := python
else ifneq (, $(shell $(WHERE) python3))
    MY_PYTHON := python3
endif

ifdef MY_PYTHON
    HAS_CRCMOD := $(shell $(MY_PYTHON) -c "import crcmod" 2>&1)
endif

all: $(TARGET)
	$(OBJCOPY) -O binary $< $<.bin

ifndef MY_PYTHON
	$(info )
	$(info !!!!!!!! PYTHON NOT FOUND, *.PACKED.BIN WON'T BE BUILT)
	$(info )
else ifneq (,$(HAS_CRCMOD))
	$(info )
	$(info !!!!!!!! CRCMOD NOT INSTALLED, *.PACKED.BIN WON'T BE BUILT)
	$(info !!!!!!!! run: pip install crcmod)
	$(info )
else
	-$(MY_PYTHON) fw-pack.py $<.bin $(AUTHOR_STRING) $(VERSION_STRING) $<.packed.bin
endif

	$(SIZE) $<

bench:
	$(MAKE) ENABLE_UART_RAW_REG_WRITE=1 all

debug:
	/opt/openocd/bin/openocd -c "bindto 0.0.0.0" -f interface/jlink.cfg -f dp32g030.cfg

flash:
	/opt/openocd/bin/openocd -c "bindto 0.0.0.0" -f interface/jlink.cfg -f dp32g030.cfg -c "write_image firmware.bin 0; shutdown;"

version.o: .FORCE

# Record the options; any change rebuilds every object.
BUILD_OPTIONS := CLANG=$(ENABLE_CLANG) SWD=$(ENABLE_SWD) LTO=$(ENABLE_LTO) RAW_REG_WRITE=$(ENABLE_UART_RAW_REG_WRITE) DEBUG=$(DEBUG)
.build-options: .FORCE
	@echo '$(BUILD_OPTIONS)' | cmp -s - $@ || echo '$(BUILD_OPTIONS)' > $@

$(OBJS): .build-options

$(TARGET): $(OBJS)
	$(LD) $(LDFLAGS) $^ -o $@ $(LIBS)

bsp/dp32g030/%.h: hardware/dp32g030/%.def

%.o: %.c | $(BSP_HEADERS)
	$(CC) $(CFLAGS) $(INC) -c $< -o $@

%.o: %.S
	$(AS) $(ASFLAGS) $< -o $@

.FORCE:

-include $(DEPS)

clean:
	$(RM) $(call FixPath, $(TARGET).bin $(TARGET).packed.bin $(TARGET) $(OBJS) $(DEPS) .build-options)

doxygen:
	doxygen
